#!/usr/bin/env bash

TEMP=$(mktemp -d)
SCRDIR=$(cd "$(dirname "$0")" && pwd)
RBYDIR=$SCRDIR/.ruby

mkdir -p $RBYDIR #Create Target


cd $TEMP

# Download and unzip ruby-install
wget -O ruby-install-0.6.0.tar.gz https://github.com/postmodern/ruby-install/archive/v0.6.0.tar.gz
tar -xzvf ruby-install-0.6.0.tar.gz

# Make ruby install
cd ruby-install-0.6.0/
make install PREFIX?=../ruby-install

# Install ruby via ruby-install
../ruby-install/bin/ruby-install --install-dir $RBYDIR ruby 2.3.1 -- --disable-install-doc

# Cleanup
cd
rm -rf $TEMP

# Set DOTFILES for rest of setup
export DOTFILES=$SCRDIR

# Install bundler
$DOTFILES/.ruby/bin/gem install bundler

# Make dot commando available
export PATH=$PATH:$DOTFILES/bin/bin

dotfiles setup
