#!/usr/bin/env bash

SCRDIR=$(cd "$(dirname "$0")" && pwd)

if ! command -v "rvm" >/dev/null 2>&1; then
    # Install rvm
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    \curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
    source $HOME/.rvm/scripts/rvm
fi


rvm requirements
rvm install 2.3

export DOTFILES=$SCRDIR

# Execute dot
$SCRDIR/bin/bin/dot
